### ISSUE TITLE
Any test data?

### ISSUE THREAD

**Issue by ValentinaBoP** [micahvista/MAMnet#1]
Hi!

It would be great to have some test data corresponding to the example code in the repository so to test if the tool runs correctly and to be able to thoroughly check the format of input data.

Thanks! :)

Valentina Peona

**Comment by micahvista** [comment]
Try this "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/PacBio_MtSinai_NIST/Baylor_NGMLR_bam_GRCh37/HG002_PB_70x_RG_HP10XtrioRTG.bam" from human sample HG002. 
Make sure input bam files are sorted, indexed, and MD taged.
