### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Flooooooooooooower** [micahvista/MAMnet#10]
Dear professor:
         I am currently using MAMnet for my project, but I have encountered an issue that I am unable to resolve. Specifically, the process always fails with a "Segmentation fault" error. Below is the MAMnet command I used for execution:
         
```
python ./MAMnet.py -bamfilepath */WZS.sort.bam -threads 1 -step 50 -INTERVAL 1e7 -genotype True -workdir ./workdir -SV_weightspath ./MAMnet/type -genotype_weightspath ./MAMnet/geno -outputpath */02.WZS/WZS_mamnet.vcf
```
         
In addition to the segmentation fault, I am also receiving the following error message:
         

```
NotImplementedError: Cannot convert a symbolic Tensor (bidirectional/forward_lstm/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported.
 ``` 
     
   I am unsure if these issues are related or if the second error is affecting the execution of my command. I would greatly appreciate your expertise and guidance on how to resolve these errors.
Thank you for your time and assistance.
Best regards,
Flooooooooooooower

**Comment by micahvista** [comment]
Dear Flooooooooooooower:

Sorry, I can't reproduce this error. Can you sent the bam file to me so I can run some test on this data. (BTW I still a stdudent.)

Best 
Hongyu Ding

**Comment by Flooooooooooooower** [comment]
> Dear Flooooooooooooower:
> 
> Sorry, I can't reproduce this error. Can you sent the bam file to me so I can run some test on this data. (BTW I still a stdudent.)
> 
> Best Hongyu Ding

Dear Hongyu Ding,
Thank you very much for your prompt response. I am pleased to inform you that I have successfully resolved the problem by updating the relevant software packages. The specific updates to my software versions are as follows:
Numpy: Updated to version 1.22.4
Python: Updated to version 3.9.15
TensorBoard: Updated to version 2.6.0
These updates were crucial for resolving my issue. I appreciate your help and support once again.
Best regards,
Flooooooooooooower

**Comment by Flooooooooooooower** [comment]
Dear Technical Support Team,

Hello!

I have encountered an issue when switching to a different dataset. Specifically, when I change the dataset, I receive a "stop signal sent to callsv" pause message. However, I noticed that there is still one thread running in the background.

Could you please advise what might be causing this issue? How can I resolve this problem?

Thank you for taking the time to read this letter, and I look forward to your response.

Sincerely

Fkooooooooooower
