### ISSUE TITLE
Failed to find any matching files for ./type

### ISSUE THREAD

**Issue by LYC-vio** [micahvista/MAMnet#3]
Hi,
Thank you very much for adding the version information! However, a new error popped out saying:
```
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./type
```
Strangely, MAMnet kept running after this error popped out. Do you have any idea about this error? By the way, MAMnet has been running for about 4 days (not finished yet) on a 56x HiFi bam file, which is unusually long (other SV calling tools typically finish in 12h). Is it because the error mentioned above stuck the pipeline?

**Comment by micahvista** [comment]
Thank you for reporting this, we have modified code and now MAMnet can specify the weights path. Please download the latest version of MAMnet and run this command "python MAMnet.py -bamfilepath *.bam -threads 16 -step 50 -INTERVAL 1e7 -genotype True -workdir ./workdir  -SV_weightspath */MAMnet/type -genotype_weightspath */MAMnet/geno".

**Comment by LYC-vio** [comment]
Thank you very much for fixing this issue. The ./type error no longer appears now, but I encountered a new error:
```
Traceback (most recent call last):
  File "/home/.conda/envs/MAMnet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/.conda/envs/MAMnet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/Softwares/MAMnet/MAMnet.py", line 298, in baseinfo_AlignedSegment
    meanvalue = np.load(workdir+'meanarray.npy').astype('float32')
  File "/home/.conda/envs/MAMnet/lib/python3.8/site-packages/numpy/lib/npyio.py", line 444, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```
I tried to manually add `allow_pickle=True` to `np.load(workdir+'meanarray.npy')` in MAMnet.py line 298, but don't know whether this would cause other problems. Do you have any suggestions?

Thanks again

**Comment by LYC-vio** [comment]
Seems that MAMnet runs smoothly with `allow_pickle=True`
